[package]
name = "Web-Server"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4"
cargo-watch = "8.5.2"
serde =  {version ="1.0.203", ferures = ["derive"]}
serde_json= "1.0"
futures = "0.3"
mongodb = "3.0"
tokio = {version= "1", features = ["full"]}


